/*
 * included from arch/x86/include/asm/unistd_64.h
 *
 * LITMUS^RT syscalls with "relative" numbers
 */
#define __LSC(x) (__NR_LITMUS + x)

#define __NR_set_rt_task_param			__LSC(0)
__SYSCALL(__NR_set_rt_task_param, sys_set_rt_task_param)
#define __NR_get_rt_task_param			__LSC(1)
__SYSCALL(__NR_get_rt_task_param, sys_get_rt_task_param)
#define __NR_complete_job	  		__LSC(2)
__SYSCALL(__NR_complete_job, sys_complete_job)
#define __NR_od_open				__LSC(3)
__SYSCALL(__NR_od_open, sys_od_open)
#define __NR_od_close				__LSC(4)
__SYSCALL(__NR_od_close, sys_od_close)
#define __NR_litmus_lock	       		__LSC(5)
__SYSCALL(__NR_litmus_lock, sys_litmus_lock)
#define __NR_litmus_unlock	       		__LSC(6)
__SYSCALL(__NR_litmus_unlock, sys_litmus_unlock)
#define __NR_query_job_no			__LSC(7)
__SYSCALL(__NR_query_job_no, sys_query_job_no)
#define __NR_wait_for_job_release		__LSC(8)
__SYSCALL(__NR_wait_for_job_release, sys_wait_for_job_release)
#define __NR_wait_for_ts_release		__LSC(9)
__SYSCALL(__NR_wait_for_ts_release, sys_wait_for_ts_release)
#define __NR_release_ts				__LSC(10)
__SYSCALL(__NR_release_ts, sys_release_ts)
#define __NR_get_rt_job_param		__LSC(11)
__SYSCALL(__NR_get_rt_job_param, sys_get_rt_job_param)
#define __NR_mark_event				__LSC(12)
__SYSCALL(__NR_mark_event, sys_mark_event)
#define __NR_null_call				__LSC(13)
__SYSCALL(__NR_null_call, sys_null_call)
#define __NR_flush_cache            __LSC(14)
__SYSCALL(__NR_flush_cache, sys_flush_cache)
#define __NR_set_cos_ipi            __LSC(15)
__SYSCALL(__NR_set_cos_ipi, sys_set_cos_ipi)
#define __NR_set_cos_lock            __LSC(16)
__SYSCALL(__NR_set_cos_lock, sys_set_cos_lock)
#define __NR_rt_wrmsr               __LSC(17)
__SYSCALL(__NR_rt_wrmsr, sys_rt_wrmsr)
#define __NR_rt_rdmsr               __LSC(18)
__SYSCALL(__NR_rt_rdmsr, sys_rt_rdmsr)
#define __NR_rt_wbinvd               __LSC(19)
__SYSCALL(__NR_rt_wbinvd, sys_rt_wbinvd)
#define __NR_set_rt_task_cps         __LSC(20)
__SYSCALL(__NR_set_rt_task_cps, sys_rt_set_rt_task_cps)
#define __NR_get_rt_task_cps         __LSC(21)
__SYSCALL(__NR_get_rt_task_cps, sys_rt_get_rt_task_cps)
#define NR_litmus_syscalls 24
